name: Run Nero bot

on:
  workflow_dispatch:    # لتشغيل البوت يدويًا من صفحة Actions
  schedule:
    - cron: '0 * * * *' # لتشغيله تلقائيًا كل ساعة (يمكنك تغيير الجدولة)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Create fbstate file
      run: echo '${{ secrets.FBSTATE }}' > account.txt

    - name: Run Nero bot
      run: node index.js
